### ISSUE TITLE
Unable to Build the Application 

### ISSUE THREAD

**Issue by jaydeep1958** [NativeScript/template-master-detail-vue#2]
vue --version 
2.9.6

nativescript --version
5.0.0-2018-10-06-12405

running on emulator :  Nexus_5X_API_25

--tns run android --bundle
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Executing before-watchPatterns hook from D:\jbm\nvue2\template-master-detail-vue\hooks\before-watchPatterns\nativescript-dev-webpack.js
Executing before-watch hook from D:\jbm\nvue2\template-master-detail-vue\hooks\before-watch\nativescript-dev-webpack.js
Running webpack for Android...
Bundling application for entryPath .\app.js...
clean-webpack-plugin: D:\jbm\nvue2\template-master-detail-vue\platforms\android\app\src\main\assets\app\**\* has been removed.
File change detected. Starting incremental webpack compilation...

webpack is watching the files…

Hash: 65fdfa578a826bbb3dfa
Version: webpack 4.20.2
Time: 9827ms
Built at: 2018-10-07 04:20:41
                                                 Asset       Size  Chunks             Chunk Names
         App_Resources/Android/drawable-xhdpi/logo.png     15 KiB          [emitted]
                                             bundle.js    120 KiB  bundle  [emitted]  bundle
                      App_Resources/Android/app.gradle  309 bytes          [emitted]
             App_Resources/Android/AndroidManifest.xml   1.41 KiB          [emitted]
    App_Resources/Android/drawable-hdpi/background.png   5.34 KiB          [emitted]
          App_Resources/Android/drawable-hdpi/icon.png   6.79 KiB          [emitted]
          App_Resources/Android/drawable-hdpi/logo.png   8.74 KiB          [emitted]
          App_Resources/Android/drawable-ldpi/icon.png   2.58 KiB          [emitted]
    App_Resources/Android/drawable-ldpi/background.png   1.57 KiB          [emitted]
          App_Resources/Android/drawable-ldpi/logo.png    3.1 KiB          [emitted]
          App_Resources/Android/drawable-mdpi/icon.png   3.35 KiB          [emitted]
    App_Resources/Android/drawable-mdpi/background.png   2.17 KiB          [emitted]
          App_Resources/Android/drawable-mdpi/logo.png   3.58 KiB          [emitted]
App_Resources/Android/drawable-nodpi/splash_screen.xml  311 bytes          [emitted]
   App_Resources/Android/drawable-xhdpi/background.png   9.72 KiB          [emitted]
         App_Resources/Android/drawable-xhdpi/icon.png   11.8 KiB          [emitted]
                                             vendor.js   1.79 MiB  vendor  [emitted]  vendor
        App_Resources/Android/drawable-xxhdpi/icon.png   14.3 KiB          [emitted]
 App_Resources/Android/drawable-xxxhdpi/background.png   21.9 KiB          [emitted]
  App_Resources/Android/drawable-xxhdpi/background.png   15.3 KiB          [emitted]
       App_Resources/Android/drawable-xxxhdpi/icon.png     19 KiB          [emitted]
            App_Resources/Android/google-services.json   1.04 KiB          [emitted]
        App_Resources/Android/drawable-xxhdpi/logo.png   19.9 KiB          [emitted]
           App_Resources/Android/values-v21/colors.xml  107 bytes          [emitted]
           App_Resources/Android/values-v21/styles.xml  920 bytes          [emitted]
       App_Resources/Android/drawable-xxxhdpi/logo.png   26.2 KiB          [emitted]
               App_Resources/Android/values/colors.xml  243 bytes          [emitted]
               App_Resources/Android/values/styles.xml   1.72 KiB          [emitted]
                                 fonts/FontAwesome.ttf    162 KiB          [emitted]
                           images/NativeScript-Vue.png   8.22 KiB          [emitted]
                                          package.json   82 bytes          [emitted]
                                            starter.js   39 bytes          [emitted]
                                   tns-java-classes.js    0 bytes          [emitted]
Entrypoint bundle = vendor.js bundle.js
[./ sync ^\.\/app\.(css|scss|less|sass)$] . sync nonrecursive ^\.\/app\.(css|scss|less|sass)$ 175 bytes {bundle} [built]
[./ sync recursive (root|page)\.(xml|css|js|ts|scss)$] . sync (root|page)\.(xml|css|js|ts|scss)$ 160 bytes {bundle} [built]
[./app.js] 2.57 KiB {bundle} [built]
[./app.scss] 20.5 KiB {bundle} [optional] [built]
[./package.json] 78 bytes {bundle} [optional] [built]
[./shared/cars/car-model.js] 472 bytes {bundle} [built]
[./shared/cars/car-service.js] 1.44 KiB {bundle} [built]
[./shared/cars/constants.js] 226 bytes {bundle} [built]
[./shared/firebase-config.js] 94 bytes {bundle} [built]
    + 222 hidden modules
Webpack compilation complete. Watching for file changes.
Webpack build done!
Executing before-checkForChanges hook from D:\jbm\nvue2\template-master-detail-vue\hooks\before-checkForChanges\firebase-copy-google-services.js
nativescript-plugin-firebase: building for same environment, not forcing prepare.
Executing before-shouldPrepare hook from D:\jbm\nvue2\template-master-detail-vue\hooks\before-shouldPrepare\nativescript-dev-webpack.js
Skipping prepare.
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from D:\jbm\nvue2\template-master-detail-vue\app\App_Resources\Android\app.gradle
Using support version 27.0.1
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: D:\jbm\nvue2\template-master-detail-vue\node_modules\nativescript-plugin-firebase\platforms\android\firebase-release.aar
         + adding aar plugin dependency: D:\jbm\nvue2\template-master-detail-vue\node_modules\nativescript-ui-listview\platforms\android\TNSListView-release.aar
         + adding aar plugin dependency: D:\jbm\nvue2\template-master-detail-vue\node_modules\nativescript-ui-core\platforms\android\TNSCore-release.aar
         + adding aar plugin dependency: D:\jbm\nvue2\template-master-detail-vue\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'org.nativescript.MasterDetail'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.
Executing after-watch hook from D:\jbm\nvue2\template-master-detail-vue\hooks\after-watch\nativescript-dev-webpack.js
Stopping webpack watch
Executing after-watch hook from D:\jbm\nvue2\template-master-detail-vue\hooks\after-watch\nativescript-dev-webpack.js
Stopping webpack watch

**Comment by bundyo** [comment]
This is a template app - it won't work on its own. You should use

```
tns create [project_name] --template tns-template-master-detail-vue
```

to create the project (replace [project_name] with a name you like) and the {N} CLI will do some additional tasks that will make the app buildable.
